# Generated by Django 5.1 on 2024-08-20 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('bid_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ask_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('daily_change_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
