# Generated by Django 5.1 on 2024-08-21 15:15

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0002_stockdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holdings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(default='', max_length=10)),
                ('volume', models.FloatField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.DeleteModel(
            name='StockData',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='date',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='name',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='price',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='profit_in_number',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='profit_in_percentage',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='symbol',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='volume',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='holdings',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trader.portfolio'),
        ),
        migrations.DeleteModel(
            name='User_Account',
        ),
        migrations.DeleteModel(
            name='User_Details',
        ),
    ]
