# Generated by Django 5.1 on 2024-09-06 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0004_stock_remove_portfolio_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='portfolio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trader.portfolio'),
            preserve_default=False,
        ),
    ]
