# Generated by Django 5.1 on 2024-09-06 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0006_alter_transaction_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='portfolio',
            field=models.ForeignKey(default=str, on_delete=django.db.models.deletion.CASCADE, to='trader.portfolio'),
        ),
    ]
