# Generated by Django 5.1 on 2024-09-06 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0007_alter_transaction_portfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='portfolio',
        ),
    ]
