# Generated by Django 5.1 on 2024-09-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0009_transaction_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(choices=[('aapl', 'AAPL'), ('tsla', 'TSLA'), ('nflx', 'NFLX'), ('msft', 'MSFT')], max_length=6)),
                ('order', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=6)),
                ('volume', models.DecimalField(decimal_places=2, default=0.01, max_digits=10)),
                ('price', models.FloatField(default=0)),
            ],
        ),
    ]
