# Generated by Django 5.1 on 2024-09-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0010_trade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='order',
            field=models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], default='Buy', max_length=6),
        ),
        migrations.AlterField(
            model_name='trade',
            name='symbol',
            field=models.CharField(choices=[('aapl', 'AAPL'), ('tsla', 'TSLA'), ('nflx', 'NFLX'), ('msft', 'MSFT')], default='AAPL', max_length=6),
        ),
    ]
