# Generated by Django 5.1 on 2024-09-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0011_alter_trade_order_alter_trade_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='symbol',
            field=models.CharField(choices=[('AAPL', 'AAPL'), ('TSLA', 'TSLA'), ('NFLX', 'NFLX'), ('MSFT', 'MSFT')], default='AAPL', max_length=6),
        ),
    ]
