# Generated by Django 5.1 on 2024-09-07 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0012_alter_trade_symbol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='price',
        ),
    ]
